volumes:
  nfs:
    driver: local
  mysql:
    driver: local
  mysql_slave:
    driver: local
  redis:
    driver: local

services:
  haproxy:
    image: haproxytech/haproxy-alpine
    container_name: haproxy_server
    networks:
      - owncloud-net
    volumes:
      - ./haconfig:/usr/local/etc/haproxy:ro
    restart: always
    ports:
      - 80:80
      - 8404:8404
    depends_on:
      - ocserver

  ocserver:
    image: owncloud/server:latest
    restart: always
    networks:
      - owncloud-net
    ports:
      - 8080-8081:8080
    depends_on:
      - mariadb_master
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS}
      - OWNCLOUD_DB_NAME=${OWNCLOUD_DB_NAME}
      - OWNCLOUD_DB_USERNAME=${OWNCLOUD_DB_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis

    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - nfs:/mnt/data

    deploy:
      replicas: 2

  mariadb_master:
    image: mariadb
    container_name: mariadb_master
    networks:
      - owncloud-net
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - ./50-server_master.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf

  mariadb_slave:
    image: mariadb
    container_name: mariadb_slave
    networks:
      - owncloud-net
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_MASTER_HOST=172.23.0.4
      - MARIADB_REPLICATION_USER=owncloud
      - MARIADB_REPLICATION_PASSWORD=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_slave:/var/lib/mysql
      - ./50-server_slave.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    depends_on:
      - mariadb_master

  redis:
    image: redis
    container_name: redis
    networks:
      - owncloud-net
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data

  ldap:
    image: osixia/openldap:latest
    networks:
      - owncloud-net
    container_name: ldap
    hostname: ldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=config_pass
      - LDAP_BASE_DN=dc=empresa,dc=com
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=empresa.com.ca.crt

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    networks:
      - owncloud-net
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "7777:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - ldap

  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    restart: unless-stopped
    privileged: true
    volumes:
      - nfs:/shared/folder
    environment:
      - SHARED_DIRECTORY=/shared/folder

networks:
  owncloud-net:
    driver: bridge
